create extension if not exists "http" with schema "extensions";


create table "public"."endpoints" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "method" character varying,
    "path" character varying,
    "duration" smallint,
    "project" bigint,
    "default_response" bigint
);


alter table "public"."endpoints" enable row level security;

create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "base_url" character varying not null
);


alter table "public"."projects" enable row level security;

create table "public"."responses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "body" json,
    "head" json,
    "code" smallint,
    "endpoint" bigint
);


alter table "public"."responses" enable row level security;

CREATE UNIQUE INDEX endpoints_pkey ON public.endpoints USING btree (id);

CREATE UNIQUE INDEX projects_base_url_key ON public.projects USING btree (base_url);

CREATE UNIQUE INDEX projects_name_key ON public.projects USING btree (name);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX responses_pkey ON public.responses USING btree (id);

alter table "public"."endpoints" add constraint "endpoints_pkey" PRIMARY KEY using index "endpoints_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."responses" add constraint "responses_pkey" PRIMARY KEY using index "responses_pkey";

alter table "public"."endpoints" add constraint "public_endpoints_default_response_fkey" FOREIGN KEY (default_response) REFERENCES endpoints(id) not valid;

alter table "public"."endpoints" validate constraint "public_endpoints_default_response_fkey";

alter table "public"."endpoints" add constraint "public_endpoints_id_fkey" FOREIGN KEY (id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."endpoints" validate constraint "public_endpoints_id_fkey";

alter table "public"."projects" add constraint "projects_base_url_key" UNIQUE using index "projects_base_url_key";

alter table "public"."projects" add constraint "projects_name_key" UNIQUE using index "projects_name_key";

alter table "public"."responses" add constraint "public_responses_endpoint_fkey" FOREIGN KEY (endpoint) REFERENCES endpoints(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."responses" validate constraint "public_responses_endpoint_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_endpoint(project_path character varying, endpoint_path character varying, method_path character varying)
 RETURNS json
 LANGUAGE plpgsql
AS $function$declare
   response json;
begin
   select json_build_object('body', responses.body, 'head', responses.head)
   into response
   from projects 
   inner join endpoints on projects.id = endpoints.project
   inner join responses on endpoints.default_response = responses.id
   where projects.base_url=project_path 
   and endpoints.path=endpoint_path
   and endpoints.method=method_path;
   
   return response;
end;$function$
;

CREATE OR REPLACE FUNCTION public.get_response(project character varying, endpoint character varying, method character varying)
 RETURNS json
 LANGUAGE plpgsql
AS $function$declare
   response json;
begin
   select json_build_object('body', responses.body, 'head', responses.head)
   into response
   from projects 
   inner join endpoints on projects.id = endpoints.project
   inner join responses on endpoints.default_response = responses.id
   where projects.base_url=project 
   and endpoints.path=endpoint
   and endpoints.method=method;
   
   return response;
end;$function$
;

grant delete on table "public"."endpoints" to "anon";

grant insert on table "public"."endpoints" to "anon";

grant references on table "public"."endpoints" to "anon";

grant select on table "public"."endpoints" to "anon";

grant trigger on table "public"."endpoints" to "anon";

grant truncate on table "public"."endpoints" to "anon";

grant update on table "public"."endpoints" to "anon";

grant delete on table "public"."endpoints" to "authenticated";

grant insert on table "public"."endpoints" to "authenticated";

grant references on table "public"."endpoints" to "authenticated";

grant select on table "public"."endpoints" to "authenticated";

grant trigger on table "public"."endpoints" to "authenticated";

grant truncate on table "public"."endpoints" to "authenticated";

grant update on table "public"."endpoints" to "authenticated";

grant delete on table "public"."endpoints" to "service_role";

grant insert on table "public"."endpoints" to "service_role";

grant references on table "public"."endpoints" to "service_role";

grant select on table "public"."endpoints" to "service_role";

grant trigger on table "public"."endpoints" to "service_role";

grant truncate on table "public"."endpoints" to "service_role";

grant update on table "public"."endpoints" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."responses" to "anon";

grant insert on table "public"."responses" to "anon";

grant references on table "public"."responses" to "anon";

grant select on table "public"."responses" to "anon";

grant trigger on table "public"."responses" to "anon";

grant truncate on table "public"."responses" to "anon";

grant update on table "public"."responses" to "anon";

grant delete on table "public"."responses" to "authenticated";

grant insert on table "public"."responses" to "authenticated";

grant references on table "public"."responses" to "authenticated";

grant select on table "public"."responses" to "authenticated";

grant trigger on table "public"."responses" to "authenticated";

grant truncate on table "public"."responses" to "authenticated";

grant update on table "public"."responses" to "authenticated";

grant delete on table "public"."responses" to "service_role";

grant insert on table "public"."responses" to "service_role";

grant references on table "public"."responses" to "service_role";

grant select on table "public"."responses" to "service_role";

grant trigger on table "public"."responses" to "service_role";

grant truncate on table "public"."responses" to "service_role";

grant update on table "public"."responses" to "service_role";


